
package Vistas;

import Controladores.CClientes;
import Controladores.CProveedores;
import Controladores.CUsuarios;
import Controladores.CProductos;
import Funciones.FondoImagen;
import Modelos.Login;
import java.awt.Dimension;
import java.awt.Toolkit;


public class FrmPrincipal extends javax.swing.JFrame {

    FondoImagen fi = new FondoImagen();
    Login lg = new Login();
    CClientes c = new CClientes();
    CProveedores p = new CProveedores();
    CUsuarios u = new CUsuarios();
    CProductos pr = new CProductos();
    FrmRegClientes clie = new FrmRegClientes();
    FrmRegProveedor prov = new FrmRegProveedor();
    FrmRegUsuarios usua = new FrmRegUsuarios();
    FrmRegProductos prod = new FrmRegProductos();
    public FrmPrincipal() {
        fi.setImage();
        setContentPane(fi);
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //int ancho = d.width, largo = (d.height)- 50;
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);
        
        lblBienvenido.setText(lblBienvenido.getText()+" "+lg.getUsua_nombre()+" "+lg.getUsua_ape());
        c.listarClientes(tblClientes);
        tblClientes.getTableHeader().setReorderingAllowed(false);
        tblClientes.setRowHeight(25);
        
        /*p.listarProveedores(tblProveedores);
        tblProveedores.getTableHeader().setReorderingAllowed(false);
        tblProveedores.setRowHeight(25);*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuCrearCliente = new javax.swing.JMenuItem();
        menuModificarCliente = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        menuCrearProveedor = new javax.swing.JMenuItem();
        menuModificarProveedor = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuCrearUsuario = new javax.swing.JMenuItem();
        menuModificarUsuario = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        menuCrearProducto = new javax.swing.JMenuItem();
        menuModificarProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setOpaque(false);

        lblBienvenido.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(1, 1, 1));
        lblBienvenido.setText("Bienvenido");

        tblClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblClientes.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Listado de Clientes");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Listado de Proveedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBienvenido)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(331, 331, 331))
        );

        menuClientes.setText("Clientes");

        menuCrearCliente.setText("Registrar Cliente");
        menuCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuCrearCliente);

        menuModificarCliente.setText("Modificar Cliente");
        menuClientes.add(menuModificarCliente);

        jMenuBar1.add(menuClientes);

        menuProveedores.setText("Proveedores");

        menuCrearProveedor.setText("Registrar Proveedor");
        menuCrearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearProveedorActionPerformed(evt);
            }
        });
        menuProveedores.add(menuCrearProveedor);

        menuModificarProveedor.setText("Modificar Proveedor");
        menuProveedores.add(menuModificarProveedor);

        jMenuBar1.add(menuProveedores);

        menuUsuarios.setText("Usuarios");

        menuCrearUsuario.setText("Registrar Usuario");
        menuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuCrearUsuario);

        menuModificarUsuario.setText("Modificar Usuario");
        menuUsuarios.add(menuModificarUsuario);

        jMenuBar1.add(menuUsuarios);

        menuProductos.setText("Productos");

        menuCrearProducto.setText("Registrar Producto");
        menuCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearProductoActionPerformed(evt);
            }
        });
        menuProductos.add(menuCrearProducto);

        menuModificarProducto.setText("Modificar Producto");
        menuProductos.add(menuModificarProducto);

        jMenuBar1.add(menuProductos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearClienteActionPerformed
        clie.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCrearClienteActionPerformed

    private void menuCrearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearProveedorActionPerformed
        prov.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCrearProveedorActionPerformed

    private void menuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearUsuarioActionPerformed
        usua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCrearUsuarioActionPerformed

    private void menuCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearProductoActionPerformed
        prod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCrearProductoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuCrearCliente;
    private javax.swing.JMenuItem menuCrearProducto;
    private javax.swing.JMenuItem menuCrearProveedor;
    private javax.swing.JMenuItem menuCrearUsuario;
    private javax.swing.JMenuItem menuModificarCliente;
    private javax.swing.JMenuItem menuModificarProducto;
    private javax.swing.JMenuItem menuModificarProveedor;
    private javax.swing.JMenuItem menuModificarUsuario;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
